version: "3.8"

services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: backend
      MYSQL_PASSWORD: 123456A
      MYSQL_ROOT_HOST: '%'

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 80:80
    expose:
      - 80
    volumes:
      - .:/backend
      - node_modules:/node_modules
    depends_on:
    -   mysql-db

volumes:
  db_data:
  node_modules:
